name: Run script

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run install_netcdf.sh
      run: bash ${GITHUB_WORKSPACE}/install_netcdf.sh
